### ISSUE TITLE
Create Product Prototype 

### ISSUE THREAD

**Issue by thomadeus** [ugo-n/graphical-image-password-authenticator#24]
# Be able to **demonstrate** #:

## 1.  Registering a  _New_  **User** : ##
- [ ] Creating a username 
- [ ] **Checking uniqueness of username**
- [ ] Password creation

## 2. **User** _interacting_ password interface
- [x] Picking sequence of emotes
- [ ] **Re-choosing choice of emote at different positions**

## 3. Registered **User** _logging_ in: ##
- [ ] Enter username
- [ ] Present password interface
- [ ] Show case of entering **INCORRECT PASSWORD** / **USERNAME**
- [ ] Show case of  **successful** login
